---
- hosts: all
  become: True
  gather_facts: True
  tasks:
  - name: check disk size
    shell: df -h
    register: disk_size

  - name: debug disk size
    debug:
      var: disk_size.stdout

  - name: remove unnecesary packages and dependencies 
    shell: sudo apt-get autoremove --purge
    register: autoremove_results

  - name: debug remove unnecesary packages
    debug:
      var: autoremove_results.stdout 

  - name: clean Thumbnail cache
    shell: sudo rm -rf ~/.cache/thmbnails/* 
    ignore_errors: yes
    register: thmbnails_results

  - name: debug thumbnail cache clean
    debug: 
      var: thmbnails_results.stdout 

  - name: check apt-cache /var/cache/apt size
    shell: du -sh /var/cache/apt | awk '{print $1}'
    register: du_results

  - name: debug /var/cache/apt size results
    debug:
      var: du_results.stdout 

  - name: clean cache 
    shell: sudo apt-get clean -y
    register: cache_clean_results

  - name: debug clean cache 
    debug:
      var: cache_clean_results.stdout